//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePropertyWithProtectedMembersDataSource : FakeDataSource<Havit.EFCoreTests.Model.PropertyWithProtectedMembers>, Havit.EFCoreTests.DataLayer.DataSources.IPropertyWithProtectedMembersDataSource
{
	public FakePropertyWithProtectedMembersDataSource(params Havit.EFCoreTests.Model.PropertyWithProtectedMembers[] data)
		: this((IEnumerable<Havit.EFCoreTests.Model.PropertyWithProtectedMembers>)data)
	{			
	}

	public FakePropertyWithProtectedMembersDataSource(IEnumerable<Havit.EFCoreTests.Model.PropertyWithProtectedMembers> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
