//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeLanguageDataSource : FakeDataSource<Havit.EFCoreTests.Model.Language>, Havit.EFCoreTests.DataLayer.DataSources.ILanguageDataSource
{
	public FakeLanguageDataSource(params Havit.EFCoreTests.Model.Language[] data)
		: this((IEnumerable<Havit.EFCoreTests.Model.Language>)data)
	{			
	}

	public FakeLanguageDataSource(IEnumerable<Havit.EFCoreTests.Model.Language> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
