name: $(Build.DefinitionName)-$(Date:yyyy-MM-dd).$(Rev:rr)B

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: pipelines
    type: git
    name: 000.HAV-Pipelines
    ref: master
    trigger: none

variables:
  - group: 002.HFW-HavitFramework
  
extends:
  template: 002.HFW-HavitFramework/Builds/002.HFW-HavitFramework.yml@pipelines
