namespace Havit.Extensions.DependencyInjection.SourceGenerators.Tests;

public partial class ServiceRegistrationsTests
{
	[TestMethod]
	public async Task ServiceRegistration_Empty()
	{
		const string input = @"public class MyService { }";

		const string expectedOutput = @"// <auto-generated/>

using Microsoft.Extensions.DependencyInjection;

namespace Havit.TestProject.Services;

public static class ServiceAttributeServiceCollectionExtensions
{
	public static IServiceCollection AddServicesByServiceAttribute(this IServiceCollection services, params string[] profileNames)
	{
		foreach (string profileName in profileNames)
		{
			AddServicesByServiceAttribute(services, profileName);
		}
		return services;
	}

	public static IServiceCollection AddServicesByServiceAttribute(this IServiceCollection services, string profileName = Havit.Extensions.DependencyInjection.Abstractions.ServiceAttribute.DefaultProfile)
	{
		return services;
	}
}
";

		await VerifyGeneratorAsync(input, expectedOutput, cancellationToken: TestContext.CancellationToken);
	}
}
