//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.Data.EntityFrameworkCore.TestSolution.Model.ModelMetadata.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class LanguageMetadata
{
	public const int CultureMaxLength = Int32.MaxValue;
	public const int NameMaxLength = 50;
	public const int UiCultureMaxLength = Int32.MaxValue;
}
