//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.WebApplicationTest.HavitWebBootstrapTests {
    
    
    public partial class NavbarTest {
        
        /// <summary>
        /// FirstNavbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.Navbar FirstNavbar;
        
        /// <summary>
        /// FirstNavbarLinkItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.NavbarLinkItem FirstNavbarLinkItem;
        
        /// <summary>
        /// WebSiteMapDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SiteMapDataSource WebSiteMapDataSource;
        
        /// <summary>
        /// SecondNavbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.Navbar SecondNavbar;
        
        /// <summary>
        /// CountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CountLabel;
    }
}
