//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.WebApplicationTest.HavitWebBootstrapTests {
    
    
    public partial class RadioButtonListTest {
        
        /// <summary>
        /// HorizontalRadioButtonList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.RadioButtonList HorizontalRadioButtonList;
        
        /// <summary>
        /// VerticalRadioButtonList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.RadioButtonList VerticalRadioButtonList;
        
        /// <summary>
        /// DynamicalyAddItemButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button DynamicalyAddItemButton;
    }
}
