//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest.HavitWebBootstrapTests {
    
    
    public partial class ValidatorsTest {
        
        /// <summary>
        /// TB1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TB1;
        
        /// <summary>
        /// SectionAButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.Button SectionAButton;
        
        /// <summary>
        /// TB3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TB3;
        
        /// <summary>
        /// SectionBButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.Button SectionBButton;
        
        /// <summary>
        /// TB5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TB5;
        
        /// <summary>
        /// ValidationTargetTestUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplicationTest.HavitWebBootstrapTests.Controls.ValidationTargetTest ValidationTargetTestUC;
        
        /// <summary>
        /// SectionDCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Havit.Web.Bootstrap.UI.WebControls.CustomValidator SectionDCustomValidator;
        
        /// <summary>
        /// ValidationTargetTest2UC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebApplicationTest.HavitWebBootstrapTests.Controls.ValidationTargetTest ValidationTargetTest2UC;
    }
}
