<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Havit Documentation Signpost</title>
	<link href="~/Content/site.css" rel="stylesheet" runat="server" />
	<style>
		.container {
			margin-top: 120px;
		}
		a.btn {
			width: 640px;
		}
		a.btn img {
			width: 200px;
			float: left;
			margin-right: 30px;
		}
	</style>
</head>

<body>
    <div class="container">
		<div class="text-center">
			
			<a href="." class="btn btn-default btn-lg"><!-- don't follow this ugly pattern -->
				<img src="Content/Images/screen-bootstrap.png" />
				Havit.Web.Bootstrap Documentation
			</a>

			<br/>
			<br/>
			<br/>
			
			<a href="/Documentation" class="btn btn-default btn-lg"><!-- don't follow this ugly pattern -->
				<img src="Content/Images/screen-hfw.png" />
				Havit Framework Extensions Documentation<br/><small>generated by SandCastle</small>
			</a>
		</div>				
    </div>
</body>
</html>
