// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Havit.Business;
namespace Havit.BusinessTest
{
	/// <summary>
	///This is a test class for Havit.Business.IdentityMap and is intended
	///to contain all Havit.Business.IdentityMap Unit Tests
	///</summary>
	[TestClass()]
	public class IdentityMapTest
	{
		#region TestContext
		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#endregion

		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion

		/// <summary>
		///A test for Store&lt;&gt; (T)
		///</summary>
		[TestMethod()]
		[ExpectedException(typeof(InvalidOperationException))]
		public void StoreTest_StoreRuznychInstanci()
		{
			IdentityMap target = new IdentityMap();

			TestingBusinessObject businessObject1 = new TestingBusinessObject(10); // TODO: Initialize to an appropriate value
			TestingBusinessObject businessObject2 = new TestingBusinessObject(10); // TODO: Initialize to an appropriate value

			target.Store(businessObject1);
			target.Store(businessObject2);
		}

		/// <summary>
		///A test for Get&lt;&gt; (int)
		///</summary>
		[TestMethod()]
		public void GetTest()
		{
			IdentityMap target = new IdentityMap();

			int id = 0; // TODO: Initialize to an appropriate value

			T expected = 0;
			T actual;

			actual = target.Get(id);

			Assert.AreEqual(expected, actual, "Havit.Business.IdentityMap.Get<T> did not return the expected value.");
			Assert.Inconclusive("Verify the correctness of this test method.");
			Assert.Inconclusive("Generics testing must be manually provided.");
		}


	}


}
