// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Havit.Business.Query;
using Havit.BusinessLayerTest;
namespace Havit.BusinessTest
{
	/// <summary>
	/// This is a test class for Havit.Business.Query.ReferenceCondition and is intended
	/// to contain all Havit.Business.Query.ReferenceCondition Unit Tests
	/// </summary>
	[TestClass]
	public class ReferenceConditionTest
	{
		#region CreateEquals
		/// <summary>
		/// A test for CreateEquals (IOperand, int?)
		/// </summary>
		[TestMethod]
		public void CreateEqualsTest_ZaporneID_Neexistujici()
		{
			IOperand operand = Subjekt.Properties.Uzivatel;
			int? id = -10145603;  // neexistující uživatel

			QueryParams qp = new QueryParams();
			qp.Conditions.Add(ReferenceCondition.CreateEquals(operand, id));
			SubjektCollection subjekty = Subjekt.GetList(qp); 

			Assert.AreEqual(subjekty.Count, 0);
		}
		#endregion
	}
}
