// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Havit.Data.EntityFrameworkCore.CodeGenerator.Actions.Repositories.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RepositoryQueryProviderTemplate : RepositoryQueryProviderTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Havit.Data.EntityFrameworkCore.Patterns.Repositories;\r\nusing Havit.Data.Ent" +
                    "ityFrameworkCore.Patterns.SoftDeletes;\r\nusing Microsoft.EntityFrameworkCore;\r\nus" +
                    "ing DbContext = Havit.Data.EntityFrameworkCore.DbContext;\r\n\r\nnamespace ");
            
            #line 11 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\ninternal class ");
            
            #line 13 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.RepositoryQueryProviderClassName));
            
            #line default
            #line hidden
            this.Write(" : IRepositoryQueryProvider<");
            
            #line 13 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 13 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\tprivate readonly ISoftDeleteManager _softDeleteManager;\r\n\r\n\tprivate readon" +
                    "ly Func<DbContext, ");
            
            #line 17 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 17 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write("> _getObjectQuery;\r\n\tprivate readonly Func<DbContext, ");
            
            #line 18 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(", CancellationToken, Task<");
            
            #line 18 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> _getObjectAsyncQuery;\r\n\tprivate readonly Func<DbContext, ");
            
            #line 19 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[], IEnumerable<");
            
            #line 19 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> _getObjectsQuery;\r\n\tprivate readonly Func<DbContext, ");
            
            #line 20 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[], IAsyncEnumerable<");
            
            #line 20 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> _getObjectsAsyncQuery;\r\n\tprivate readonly Func<DbContext, IEnumerable<");
            
            #line 21 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> _getAllQuery;\r\n\tprivate readonly Func<DbContext, IAsyncEnumerable<");
            
            #line 22 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> _getAllAsyncQuery;\r\n\r\n\tpublic ");
            
            #line 24 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.RepositoryQueryProviderClassName));
            
            #line default
            #line hidden
            this.Write("(ISoftDeleteManager softDeleteManager)\r\n\t{\r\n\t\t_softDeleteManager = softDeleteMana" +
                    "ger;\r\n\r\n\t\t_getObjectQuery = EF.CompileQuery((DbContext dbContext, ");
            
            #line 28 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(" id) => dbContext\r\n\t\t\t.Set<");
            
            #line 29 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 30 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 30 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 30 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 30 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetObject)))\r\n\t\t\t.Where(entity => entity.");
            
            #line 31 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write(" == id)\r\n\t\t\t.FirstOrDefault());\r\n\r\n\t\t_getObjectAsyncQuery = EF.CompileAsyncQuery(" +
                    "(DbContext dbContext, ");
            
            #line 34 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(" id, CancellationToken cancellationToken) => dbContext\r\n\t\t\t.Set<");
            
            #line 35 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 36 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 36 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 36 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 36 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetObjectAsync)))\r\n\t\t\t.Where(entity => entity.");
            
            #line 37 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write(" == id)\r\n\t\t\t.FirstOrDefault());\r\n\r\n\t\t_getObjectsQuery = EF.CompileQuery((DbContex" +
                    "t dbContext, ");
            
            #line 40 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[] ids) => dbContext\r\n\t\t\t.Set<");
            
            #line 41 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 42 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 42 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 42 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 42 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetObjects)))\r\n\t\t\t.Where(entity => ids.Contains(entity.");
            
            #line 43 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write(")));\r\n\r\n\t\t_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, ");
            
            #line 45 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[] ids) => dbContext\r\n\t\t\t.Set<");
            
            #line 46 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 47 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 47 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 47 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 47 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetObjectsAsync)))\r\n\t\t\t.Where(entity => ids.Contains(entity.");
            
            #line 48 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write(")));\r\n\r\n\t\t_getAllQuery = EF.CompileQuery((DbContext dbContext) => dbContext\r\n\t\t\t." +
                    "Set<");
            
            #line 51 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 52 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 52 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 52 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 52 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetAll)))\r\n\t\t\t.WhereNotDeleted(_softDeleteManager));\r\n\r\n\t\t_getAllAsyncQuery = E" +
                    "F.CompileAsyncQuery((DbContext dbContext) => dbContext\r\n\t\t\t.Set<");
            
            #line 56 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t.TagWith(Data.EntityFrameworkCore.QueryTagBuilder.CreateTag(typeof(");
            
            #line 57 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.NamespaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 57 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DbRepositoryName));
            
            #line default
            #line hidden
            this.Write("), nameof(Data.Patterns.Repositories.IRepository<");
            
            #line 57 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 57 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(">.GetAllAsync)))\r\n\t\t\t.WhereNotDeleted(_softDeleteManager));\r\n\t}\r\n\r\n\tpublic Func<D" +
                    "bContext, ");
            
            #line 61 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 61 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write("> GetGetObjectQuery() => _getObjectQuery;\r\n\tpublic Func<DbContext, ");
            
            #line 62 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write(", CancellationToken, Task<");
            
            #line 62 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;\r\n\tpublic Func<DbContext, ");
            
            #line 63 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[], IEnumerable<");
            
            #line 63 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> GetGetObjectsQuery() => _getObjectsQuery;\r\n\tpublic Func<DbContext, ");
            
            #line 64 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassPrimaryKeyTypeName));
            
            #line default
            #line hidden
            this.Write("[], IAsyncEnumerable<");
            
            #line 64 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;\r\n\tpublic Func<DbContext, I" +
                    "AsyncEnumerable<");
            
            #line 65 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> GetGetAllAsyncQuery() => _getAllAsyncQuery;\r\n\tpublic Func<DbContext, IEnumerab" +
                    "le<");
            
            #line 66 "D:\Dev\002.HFW-HavitFramework\Havit.Data.EntityFrameworkCore.CodeGenerator\Actions\Repositories\Templates\RepositoryQueryProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelClassFullName));
            
            #line default
            #line hidden
            this.Write(">> GetGetAllQuery() => _getAllQuery;\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class RepositoryQueryProviderTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
