//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Caching;
using System.Xml;
using Havit.Business;
using Havit.Business.Query;
using Havit.Collections;
using Havit.Data;
using Havit.Data.SqlServer;
using Havit.Data.SqlTypes;

namespace Havit.BusinessLayerTest
{
	/// <summary>
	/// Test pro money.
	/// </summary>
	/// <remarks>
	/// <code>
	/// CREATE TABLE [dbo].[CenikItem](
	/// 	[CenikItemID] [int] IDENTITY(1,1) NOT NULL,
	/// 	[CenaAmount] [money] NOT NULL,
	/// 	[CenaCurrencyID] [int] NOT NULL,
	///  CONSTRAINT [PK_CenikItem] PRIMARY KEY CLUSTERED 
	/// (
	/// 	[CenikItemID] ASC
	/// )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	/// ) ON [PRIMARY]
	/// ALTER TABLE [dbo].[CenikItem]  WITH NOCHECK ADD  CONSTRAINT [FK_CenikItem_Currency] FOREIGN KEY([CenaCurrencyID])
	/// REFERENCES [dbo].[Currency] ([CurrencyID])
	/// ALTER TABLE [dbo].[CenikItem] CHECK CONSTRAINT [FK_CenikItem_Currency]
	/// </code>
	/// </remarks>
	[System.CodeDom.Compiler.GeneratedCode("Havit.BusinessLayerGenerator", "1.0")]
	public abstract class CenikItemBase : ActiveRecordBusinessObjectBase
	{
		#region Static constructor
		static CenikItemBase()
		{
			objectInfo = new ObjectInfo();
			properties = new CenikItemProperties();
			objectInfo.Initialize("dbo", "CenikItem", "CenikItem", "Havit.BusinessLayerTest", false, CenikItem.CreateObject, CenikItem.GetObject, CenikItem.GetAll, null, properties.All);
			properties.Initialize(objectInfo);
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// Vytvoří instanci objektu jako nový prvek.
		/// </summary>
		/// <param name="connectionMode">Režim business objektu.</param>
		[System.CodeDom.Compiler.GeneratedCode("Havit.BusinessLayerGenerator", "1.0")]
		protected CenikItemBase(ConnectionMode connectionMode) : base(connectionMode)
		{
		}
		
		/// <summary>
		/// Vytvoří instanci existujícího objektu.
		/// </summary>
		/// <param name="id">CenikItemID (PK).</param>
		/// <param name="connectionMode">Režim business objektu.</param>
		protected CenikItemBase(int id, ConnectionMode connectionMode) : base(id, connectionMode)
		{
		}
		
		/// <summary>
		/// Vytvoří instanci objektu na základě dat (i částečných) načtených z databáze.
		/// </summary>
		/// <param name="id">CenikItemID (PK).</param>
		/// <param name="record">DataRecord s daty objektu (i částečnými).</param>
		protected CenikItemBase(int id, DataRecord record) : base(id, record)
		{
		}
		#endregion
		
		#region Properties dle sloupců databázové tabulky
		/// <summary>
		/// Cena. [money, not-null]
		/// </summary>
		public virtual Decimal CenaAmount
		{
			get
			{
				EnsureLoaded();
				return _CenaAmountPropertyHolder.Value;
			}
			set
			{
				EnsureLoaded();
				if (value != _CenaAmountPropertyHolder.Value)
				{
					_cenaIsUpToDate = false;
				}
				_CenaAmountPropertyHolder.Value = value;
			}
		}
		/// <summary>
		/// PropertyHolder pro vlastnost CenaAmount.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected PropertyHolder<Decimal> _CenaAmountPropertyHolder;
		
		/// <summary>
		/// Cena (měna). [int, not-null]
		/// </summary>
		public virtual Havit.BusinessLayerTest.Currency CenaCurrency
		{
			get
			{
				EnsureLoaded();
				return _CenaCurrencyPropertyHolder.Value;
			}
			set
			{
				EnsureLoaded();
				if (value != _CenaCurrencyPropertyHolder.Value)
				{
					_cenaIsUpToDate = false;
				}
				_CenaCurrencyPropertyHolder.Value = value;
			}
		}
		/// <summary>
		/// PropertyHolder pro vlastnost CenaCurrency.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected PropertyHolder<Havit.BusinessLayerTest.Currency> _CenaCurrencyPropertyHolder;
		
		/// <summary>
		/// Cena.
		/// </summary>
		public virtual Havit.BusinessLayerTest.Money Cena
		{
			get
			{
				EnsureLoaded();
				if (!_cenaIsUpToDate)
				{
					_cena = new Havit.BusinessLayerTest.Money(CenaAmount, CenaCurrency);
					_cenaIsUpToDate = true;
				}
				return _cena;
			}
			set
			{
				EnsureLoaded();
				if (value == null)
				{
					throw new InvalidOperationException("Value is null but cannot be set to not-null CenaAmount property.");
				}
				if (value.Amount == null)
				{
					throw new InvalidOperationException("Amount is null but cannot be set to not-null CenaAmount property.");
				}
				CenaAmount = value.Amount.Value;
				CenaCurrency = value.Currency;
				_cena = value;
				_cenaIsUpToDate = true;
			}
		}
		private Havit.BusinessLayerTest.Money _cena;
		private bool _cenaIsUpToDate;
		
		#endregion
		
		#region Init
		/// <summary>
		/// Inicializuje třídu (vytvoří instance PropertyHolderů).
		/// </summary>
		protected override void Init()
		{
			_CenaAmountPropertyHolder = new PropertyHolder<Decimal>(this);
			_CenaCurrencyPropertyHolder = new PropertyHolder<Havit.BusinessLayerTest.Currency>(this);
			
			if (IsNew || IsDisconnected)
			{
				_CenaAmountPropertyHolder.Value = default(Decimal);
				_CenaCurrencyPropertyHolder.Value = null;
			}
			
			base.Init();
		}
		#endregion
		
		#region CleanDirty
		/// <summary>
		/// Nastaví property holderům IsDirty na false.
		/// </summary>
		protected override void CleanDirty()
		{
			base.CleanDirty();
			
			_CenaAmountPropertyHolder.IsDirty = false;
			_CenaCurrencyPropertyHolder.IsDirty = false;
		}
		#endregion
		
		#region CheckConstraints
		/// <summary>
		/// Kontroluje konzistenci objektu jako celku.
		/// </summary>
		/// <remarks>
		/// Automaticky je voláno před ukládáním objektu Save(), pokud je objekt opravdu ukládán.
		/// </remarks>
		protected override void CheckConstraints()
		{
			base.CheckConstraints();
			
			if (_CenaCurrencyPropertyHolder.IsDirty && (_CenaCurrencyPropertyHolder.Value == null))
			{
				throw new ConstraintViolationException(this, "Vlastnost \"CenaCurrency\" nesmí nabývat hodnoty null.");
			}
			
		}
		#endregion
		
		#region Load: Load_GetDataRecord, Load_ParseDataRecord
		/// <summary>
		/// Načte data objektu z DB a vrátí je ve formě DataRecordu.
		/// </summary>
		/// <param name="transaction">Transakce.</param>
		/// <returns>Úplná data objektu.</returns>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed DataRecord Load_GetDataRecord(DbTransaction transaction)
		{
			DataRecord result;
			
			DbCommand dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.CommandText = "SELECT [CenikItemID], [CenaAmount], [CenaCurrencyID] FROM [dbo].[CenikItem] WHERE [CenikItemID] = @CenikItemID";
			dbCommand.Transaction = transaction;
			
			DbParameter dbParameterCenikItemID = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenikItemID.DbType = DbType.Int32;
			dbParameterCenikItemID.Direction = ParameterDirection.Input;
			dbParameterCenikItemID.ParameterName = "CenikItemID";
			dbParameterCenikItemID.Value = this.ID;
			dbCommand.Parameters.Add(dbParameterCenikItemID);
			
			result = DbConnector.Default.ExecuteDataRecord(dbCommand);
			
			return result;
		}
		
		/// <summary>
		/// Vytahá data objektu z DataRecordu.
		/// </summary>
		/// <param name="record">DataRecord s daty objektu</param>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Load_ParseDataRecord(DataRecord record)
		{
			this.ID = record.Get<int>("CenikItemID");
			
			Decimal _tempCenaAmount;
			if (record.TryGet<Decimal>("CenaAmount", out _tempCenaAmount))
			{
				_CenaAmountPropertyHolder.Value = _tempCenaAmount;
			}
			
			int _tempCenaCurrency;
			if (record.TryGet<int>("CenaCurrencyID", out _tempCenaCurrency))
			{
				_CenaCurrencyPropertyHolder.Value = Havit.BusinessLayerTest.Currency.GetObject(_tempCenaCurrency);
			}
			
		}
		#endregion
		
		#region Save & Delete: Save_SaveMembers, Save_SaveCollections, Save_MinimalInsert, Save_FullInsert, Save_Update, Save_Insert_InsertRequiredForMinimalInsert, Save_Insert_InsertRequiredForFullInsert, Delete, Delete_Perform
		
		/// <summary>
		/// Ukládá member-objekty.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_SaveMembers(DbTransaction transaction)
		{
			base.Save_SaveMembers(transaction);
			
			if (_CenaCurrencyPropertyHolder.IsInitialized && (_CenaCurrencyPropertyHolder.Value != null))
			{
				_CenaCurrencyPropertyHolder.Value.Save(transaction);
			}
			
		}
		
		/// <summary>
		/// Ukládá member-kolekce objektu.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_SaveCollections(DbTransaction transaction)
		{
			base.Save_SaveCollections(transaction);
			
			// Není co ukládat.
		}
		
		/// <summary>
		/// Implementace metody vloží jen not-null vlastnosti objektu do databáze a nastaví nově přidělené ID (primární klíč).
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public override sealed void Save_MinimalInsert(DbTransaction transaction)
		{
			base.Save_MinimalInsert(transaction);
			Save_Insert_InsertRequiredForMinimalInsert(transaction);
			
			DbCommand dbCommand;
			dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.Transaction = transaction;
			
			DbParameter dbParameterCenaAmount = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenaAmount.DbType = DbType.Decimal;
			dbParameterCenaAmount.Direction = ParameterDirection.Input;
			dbParameterCenaAmount.ParameterName = "CenaAmount";
			dbParameterCenaAmount.Value = _CenaAmountPropertyHolder.Value;
			dbCommand.Parameters.Add(dbParameterCenaAmount);
			_CenaAmountPropertyHolder.IsDirty = false;
			
			DbParameter dbParameterCenaCurrencyID = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenaCurrencyID.DbType = DbType.Int32;
			dbParameterCenaCurrencyID.Direction = ParameterDirection.Input;
			dbParameterCenaCurrencyID.ParameterName = "CenaCurrencyID";
			dbParameterCenaCurrencyID.Value = (_CenaCurrencyPropertyHolder.Value == null) ? DBNull.Value : (object)_CenaCurrencyPropertyHolder.Value.ID;
			dbCommand.Parameters.Add(dbParameterCenaCurrencyID);
			_CenaCurrencyPropertyHolder.IsDirty = false;
			
			dbCommand.CommandText = "DECLARE @CenikItemID INT; INSERT INTO [dbo].[CenikItem] ([CenaAmount], [CenaCurrencyID]) VALUES (@CenaAmount, @CenaCurrencyID); SELECT @CenikItemID = SCOPE_IDENTITY(); SELECT @CenikItemID; ";
			this.ID = (int)DbConnector.Default.ExecuteScalar(dbCommand);
			this.IsNew = false; // uložený objekt není už nový, dostal i přidělené ID
			
			IdentityMap currentIdentityMap = IdentityMapScope.Current;
			global::Havit.Diagnostics.Contracts.Contract.Assert(currentIdentityMap != null, "currentIdentityMap != null");
			currentIdentityMap.Store(this);
		}
		
		/// <summary>
		/// Implementace metody vloží nový objekt do databáze a nastaví nově přidělené ID (primární klíč).
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_FullInsert(DbTransaction transaction)
		{
			DbCommand dbCommand;
			dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.Transaction = transaction;
			
			DbParameter dbParameterCenaAmount = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenaAmount.DbType = DbType.Decimal;
			dbParameterCenaAmount.Direction = ParameterDirection.Input;
			dbParameterCenaAmount.ParameterName = "CenaAmount";
			dbParameterCenaAmount.Value = _CenaAmountPropertyHolder.Value;
			dbCommand.Parameters.Add(dbParameterCenaAmount);
			_CenaAmountPropertyHolder.IsDirty = false;
			
			DbParameter dbParameterCenaCurrencyID = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenaCurrencyID.DbType = DbType.Int32;
			dbParameterCenaCurrencyID.Direction = ParameterDirection.Input;
			dbParameterCenaCurrencyID.ParameterName = "CenaCurrencyID";
			dbParameterCenaCurrencyID.Value = (_CenaCurrencyPropertyHolder.Value == null) ? DBNull.Value : (object)_CenaCurrencyPropertyHolder.Value.ID;
			dbCommand.Parameters.Add(dbParameterCenaCurrencyID);
			_CenaCurrencyPropertyHolder.IsDirty = false;
			
			dbCommand.CommandText = "DECLARE @CenikItemID INT; INSERT INTO [dbo].[CenikItem] ([CenaAmount], [CenaCurrencyID]) VALUES (@CenaAmount, @CenaCurrencyID); SELECT @CenikItemID = SCOPE_IDENTITY(); SELECT @CenikItemID; ";
			this.ID = (int)DbConnector.Default.ExecuteScalar(dbCommand);
			this.IsNew = false; // uložený objekt není už nový, dostal i přidělené ID
			
			IdentityMap currentIdentityMap = IdentityMapScope.Current;
			global::Havit.Diagnostics.Contracts.Contract.Assert(currentIdentityMap != null, "currentIdentityMap != null");
			currentIdentityMap.Store(this);
			
			InvalidateAnySaveCacheDependencyKey();
		}
		
		/// <summary>
		/// Implementace metody aktualizuje data objektu v databázi.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_Update(DbTransaction transaction)
		{
			DbCommand dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.Transaction = transaction;
			
			StringBuilder commandBuilder = new StringBuilder();
			commandBuilder.Append("UPDATE [dbo].[CenikItem] SET ");
			
			bool dirtyFieldExists = false;
			if (_CenaAmountPropertyHolder.IsDirty)
			{
				if (dirtyFieldExists)
				{
					commandBuilder.Append(", ");
				}
				commandBuilder.Append("[CenaAmount] = @CenaAmount");
				
				DbParameter dbParameterCenaAmount = DbConnector.Default.ProviderFactory.CreateParameter();
				dbParameterCenaAmount.DbType = DbType.Decimal;
				dbParameterCenaAmount.Direction = ParameterDirection.Input;
				dbParameterCenaAmount.ParameterName = "CenaAmount";
				dbParameterCenaAmount.Value = _CenaAmountPropertyHolder.Value;
				dbCommand.Parameters.Add(dbParameterCenaAmount);
				
				dirtyFieldExists = true;
			}
			
			if (_CenaCurrencyPropertyHolder.IsDirty)
			{
				if (dirtyFieldExists)
				{
					commandBuilder.Append(", ");
				}
				commandBuilder.Append("[CenaCurrencyID] = @CenaCurrencyID");
				
				DbParameter dbParameterCenaCurrencyID = DbConnector.Default.ProviderFactory.CreateParameter();
				dbParameterCenaCurrencyID.DbType = DbType.Int32;
				dbParameterCenaCurrencyID.Direction = ParameterDirection.Input;
				dbParameterCenaCurrencyID.ParameterName = "CenaCurrencyID";
				dbParameterCenaCurrencyID.Value = (_CenaCurrencyPropertyHolder.Value == null) ? DBNull.Value : (object)_CenaCurrencyPropertyHolder.Value.ID;
				dbCommand.Parameters.Add(dbParameterCenaCurrencyID);
				
				dirtyFieldExists = true;
			}
			
			if (dirtyFieldExists)
			{
				// objekt je sice IsDirty (volá se tato metoda), ale může být změněná jen kolekce
				commandBuilder.Append(" WHERE [CenikItemID] = @CenikItemID; ");
			}
			else
			{
				commandBuilder = new StringBuilder();
			}
			
			bool dirtyCollectionExists = false;
			// pokud je objekt dirty, ale žádná property není dirty (Save_MinimalInsert poukládal všechno), neukládáme
			if (dirtyFieldExists || dirtyCollectionExists)
			{
				DbParameter dbParameterCenikItemID = DbConnector.Default.ProviderFactory.CreateParameter();
				dbParameterCenikItemID.DbType = DbType.Int32;
				dbParameterCenikItemID.Direction = ParameterDirection.Input;
				dbParameterCenikItemID.ParameterName = "CenikItemID";
				dbParameterCenikItemID.Value = this.ID;
				dbCommand.Parameters.Add(dbParameterCenikItemID);
				dbCommand.CommandText = commandBuilder.ToString();
				DbConnector.Default.ExecuteNonQuery(dbCommand);
			}
			
			InvalidateSaveCacheDependencyKey();
			InvalidateAnySaveCacheDependencyKey();
		}
		
		/// <summary>
		/// Ukládá hodnoty potřebné pro provedení minimálního insertu. Volá Save_Insert_SaveRequiredForMinimalInsert.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_Insert_InsertRequiredForMinimalInsert(DbTransaction transaction)
		{
			base.Save_Insert_InsertRequiredForMinimalInsert(transaction);
			
			if (_CenaCurrencyPropertyHolder.Value.IsNew)
			{
				_CenaCurrencyPropertyHolder.Value.Save_MinimalInsert(transaction);
			}
			
		}
		
		/// <summary>
		/// Ukládá hodnoty potřebné pro provedení plného insertu.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Save_Insert_InsertRequiredForFullInsert(DbTransaction transaction)
		{
			base.Save_Insert_InsertRequiredForFullInsert(transaction);
			
		}
		
		/// <summary>
		/// Metoda vymaže objekt z perzistentního uložiště.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected override sealed void Delete_Perform(DbTransaction transaction)
		{
			DbCommand dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.Transaction = transaction;
			
			StringBuilder commandBuilder = new StringBuilder();
			commandBuilder.AppendFormat("DELETE FROM [dbo].[CenikItem] WHERE [CenikItemID] = @CenikItemID");
			
			DbParameter dbParameterCenikItemID = DbConnector.Default.ProviderFactory.CreateParameter();
			dbParameterCenikItemID.DbType = DbType.Int32;
			dbParameterCenikItemID.Direction = ParameterDirection.Input;
			dbParameterCenikItemID.ParameterName = "CenikItemID";
			dbParameterCenikItemID.Value = this.ID;
			dbCommand.Parameters.Add(dbParameterCenikItemID);
			
			dbCommand.CommandText = commandBuilder.ToString();
			DbConnector.Default.ExecuteNonQuery(dbCommand);
			
			InvalidateSaveCacheDependencyKey();
			InvalidateAnySaveCacheDependencyKey();
		}
		
		#endregion
		
		#region Cache dependencies methods
		/// <summary>
		/// Vrátí klíč pro tvorbu závislostí cache na objektu. Při uložení objektu jsou závislosti invalidovány.
		/// </summary>
		public string GetSaveCacheDependencyKey(bool ensureInCache = true)
		{
			global::Havit.Diagnostics.Contracts.Contract.Requires(!this.IsNew, "!this.IsNew");
			
			if (!Havit.Business.BusinessLayerContext.BusinessLayerCacheService.SupportsCacheDependencies)
			{
				throw new InvalidOperationException("Použitá BusinessLayerCacheService nepodporuje cache dependencies.");
			}
			
			string key = "CenikItem.SaveCacheDependencyKey|ID=" + this.ID.ToString();
			
			if (ensureInCache)
			{
				Havit.Business.BusinessLayerContext.BusinessLayerCacheService.EnsureCacheDependencyKey(typeof(CenikItem), key);
			}
			
			return key;
		}
		
		/// <summary>
		/// Odstraní z cache závislosti na klíči CacheDependencyKey.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected void InvalidateSaveCacheDependencyKey()
		{
			if (Havit.Business.BusinessLayerContext.BusinessLayerCacheService.SupportsCacheDependencies)
			{
				Havit.Business.BusinessLayerContext.BusinessLayerCacheService.InvalidateCacheDependencies(typeof(CenikItem), GetSaveCacheDependencyKey(false));
			}
		}
		
		/// <summary>
		/// Vrátí klíč pro tvorbu závislostí cache. Po uložení jakéhokoliv objektu této třídy jsou závislosti invalidovány.
		/// </summary>
		public static string GetAnySaveCacheDependencyKey(bool ensureInCache = true)
		{
			if (!Havit.Business.BusinessLayerContext.BusinessLayerCacheService.SupportsCacheDependencies)
			{
				throw new InvalidOperationException("Použitá BusinessLayerCacheService nepodporuje cache dependencies.");
			}
			
			string key = "CenikItem.AnySaveCacheDependencyKey";
			
			if (ensureInCache)
			{
				Havit.Business.BusinessLayerContext.BusinessLayerCacheService.EnsureCacheDependencyKey(typeof(CenikItem), key);
			}
			
			return key;
		}
		
		/// <summary>
		/// Odstraní z cache závislosti na klíči AnySaveCacheDependencyKey.
		/// </summary>
		[System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		protected static void InvalidateAnySaveCacheDependencyKey()
		{
			if (Havit.Business.BusinessLayerContext.BusinessLayerCacheService.SupportsCacheDependencies)
			{
				Havit.Business.BusinessLayerContext.BusinessLayerCacheService.InvalidateCacheDependencies(typeof(CenikItem), GetAnySaveCacheDependencyKey(false));
			}
		}
		#endregion
		
		#region GetFirst, GetList, GetAll
		/// <summary>
		/// Vrátí první nalezený objekt typu CenikItem dle parametrů v queryParams.
		/// Pokud není žádný objekt nalezen, vrací null.
		/// </summary>
		public static CenikItem GetFirst(QueryParams queryParams)
		{
			global::Havit.Diagnostics.Contracts.Contract.Requires(queryParams != null, "queryParams != null");
			
			return CenikItem.GetFirst(queryParams, null);
		}
		
		/// <summary>
		/// Vrátí první nalezený objekt typu CenikItem dle parametrů v queryParams.
		/// Pokud není žádný objekt nalezen, vrací null. Data jsou načítána v předané transakci.
		/// </summary>
		public static CenikItem GetFirst(QueryParams queryParams, DbTransaction transaction)
		{
			global::Havit.Diagnostics.Contracts.Contract.Requires(queryParams != null, "queryParams != null");
			
			int? originalTopRecords = queryParams.TopRecords;
			queryParams.TopRecords = 1;
			CenikItemCollection getListResult = CenikItem.GetList(queryParams, transaction);
			queryParams.TopRecords = originalTopRecords;
			return (getListResult.Count == 0) ? null : getListResult[0];
		}
		
		/// <summary>
		/// Vrátí objekty typu CenikItem dle parametrů v queryParams.
		/// </summary>
		internal static CenikItemCollection GetList(QueryParams queryParams)
		{
			global::Havit.Diagnostics.Contracts.Contract.Requires(queryParams != null, "queryParams != null");
			
			return CenikItem.GetList(queryParams, null);
		}
		
		/// <summary>
		/// Vrátí objekty typu CenikItem dle parametrů v queryParams. Data jsou načítána v předané transakci.
		/// </summary>
		internal static CenikItemCollection GetList(QueryParams queryParams, DbTransaction transaction)
		{
			global::Havit.Diagnostics.Contracts.Contract.Requires(queryParams != null, "queryParams != null");
			
			DbCommand dbCommand = DbConnector.Default.ProviderFactory.CreateCommand();
			dbCommand.Transaction = transaction;
			
			queryParams.ObjectInfo = CenikItem.ObjectInfo;
			if (queryParams.Properties.Count > 0)
			{
				queryParams.Properties.Add(CenikItem.Properties.ID);
			}
			
			queryParams.PrepareCommand(dbCommand, SqlServerPlatform.SqlServer2008, CommandBuilderOptions.None);
			return CenikItem.GetList(dbCommand, queryParams.GetDataLoadPower());
		}
		
		private static CenikItemCollection GetList(DbCommand dbCommand, DataLoadPower dataLoadPower)
		{
			if (dbCommand == null)
			{
				throw new ArgumentNullException("dbCommand");
			}
			
			CenikItemCollection result = new CenikItemCollection();
			
			using (DbDataReader reader = DbConnector.Default.ExecuteReader(dbCommand))
			{
				while (reader.Read())
				{
					DataRecord dataRecord = new DataRecord(reader, dataLoadPower);
					CenikItem cenikItem = CenikItem.GetObject(dataRecord);
					result.Add(cenikItem);
				}
			}
			
			return result;
		}
		
		/// <summary>
		/// Vrátí všechny objekty typu CenikItem.
		/// </summary>
		public static CenikItemCollection GetAll()
		{
			CenikItemCollection collection = null;
			QueryParams queryParams = new QueryParams();
			collection = CenikItem.GetList(queryParams);
			return collection;
		}
		
		#endregion
		
		#region ToString
		/// <summary>
		/// Returns a string that represents the current object.
		/// </summary>
		public override string ToString()
		{
			if (IsNew)
			{
				return "CenikItem(New)";
			}
			
			return String.Format("CenikItem(ID={0})", this.ID);
		}
		#endregion
		
		#region ObjectInfo
		/// <summary>
		/// Objektová reprezentace metadat typu CenikItem.
		/// </summary>
		public static ObjectInfo ObjectInfo
		{
			get
			{
				return objectInfo;
			}
		}
		private static ObjectInfo objectInfo;
		#endregion
		
		#region Properties
		/// <summary>
		/// Objektová reprezentace metadat vlastností typu CenikItem.
		/// </summary>
		public static CenikItemProperties Properties
		{
			get
			{
				return properties;
			}
		}
		private static CenikItemProperties properties;
		#endregion
		
	}
}
