<%@ Page Title="" Language="C#" MasterPageFile="~/Templates/Main.Master" %>
<%@ Register TagPrefix="uc" TagName="NavbarBasicSample" Src="~/sections/controls/samples/NavbarBasicSample.ascx" %>
<%@ Register TagPrefix="uc" TagName="Menu" Src="~/Templates/Menu.ascx" %>

<asp:Content ContentPlaceHolderID="TopCPH" runat="server">
	<h1>Navbar</h1>
	<p>ASP.NET wrapper for Bootstrap Navbar</p>
</asp:Content>

<asp:Content ContentPlaceHolderID="MainCPH" runat="server">
	<h2>Appearance</h2>
	<p>Displays menu as <a href="http://getbootstrap.com/components/#navbar">Bootstrap Navbar</a>.</p>

	<h2>Properties</h2>
	<ul>
		<li>CssClass (default "navbar navbar-default") - css class for navbar element.</li>
		<li>ContainerMode (default ContainerFluid) - style of rendering container element (container/container-fluid/no container element).</li>
		<li>BrandUrl (default "~/") - url for brand a element (when set to an empty string, a element is not rendered and can be used in BrandTemplate)</li>
		<li>BrandTemplate - template for brand section (see below), when not set, whole brand section is not rendered</li>
		<li>MenuItems - menu items</li>
		<li>ShowCaret (default False) - when true, renders caret for items with children</li>
		<li>RightMenuItems - right menu items</li>
		<li>DataSource, DataSourceID - data source properties (databinding from SiteMapDataSource supported)</li>
		<li>ToggleNavigationText (default String.Empty) - text to be used for screen readers as toggle navigation text (then not used, whole element not rendered)</li>
	</ul>
	
	<h3>Menu Items</h3>
	<ul>
		<li>NavberLinkItem (Text, Url, Visible, VisibleFunc, AutoHide, Items)</li>
		<li>NavberHeaderItem (Text, Visible, VisibleFunc)</li>
		<li>NavberSeparatorItem (Text, Visible, VisibleFunc)</li>
		<li>NavberTextItem (Text)</li>
	</ul>

	<h2>Rendered HTML</h2>
	<pre>&lt;nav class=&quot;<span class="hightlight">CssClass</span>&quot; role=&quot;navigation&quot;&gt;
	&lt;div class=&quot;<span class="hightlight">ContainerMode</span>&quot;&gt;
		&lt;div class=&quot;navbar-header&quot;&gt;
			&lt;button type=&quot;button&quot; class=&quot;navbar-toggle&quot; data-toggle=&quot;collapse&quot; data-target=&quot;(autogenerated)&quot;&gt;
				&lt;span class=&quot;sr-only&quot;&gt;<span class="hightlight">ToggleNavigationText</span>&lt;/span&gt;
				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
				&lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
			&lt;/button&gt;
			&lt;a class=&quot;navbar-brand&quot; href=&quot;<span class="hightlight">BrandUrl</span>&quot;&gt;
				<span class="hightlight">BrandTemplate</span>
			&lt;/a&gt;
		&lt;/div&gt;
		&lt;div class=&quot;collapse navbar-collapse&quot; id=&quot;(autogenerated)&quot;&gt;
			&lt;ul class=&quot;nav navbar-nav&quot;&gt;
				<span class="hightlight">(html for) MenuItems</span>
			&lt;/ul&gt;
			&lt;ul class=&quot;nav navbar-nav navbar-right&quot;&gt;
				<span class="hightlight">RightMenuItems</span>	
			&lt;/ul&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/nav&gt;</pre>

	<h2>Navbar basic sample</h2>
	<uc:NavbarBasicSample runat="server" ID="NavbarBasicSample" />
	<uc:ShowControl ShowControlID="NavbarBasicSample" runat="server" />

	<h2>Navbar with sitemap demo</h2>
	<p>See main menu on top of the page.</p>
	<uc:Menu ID="NavbarSitemapSample" Visible="false" runat="server" />
	<uc:ShowControl ShowControlID="NavbarSitemapSample" runat="server" />
	<uc:ShowControl Title="Show Web.sitemap" Filename="~/Web.sitemap" runat="server" />

</asp:Content>
